sudo: required
os:
  - osx
language: ruby
rvm:
  - 2.3.0
env:
  - TRAVIS_NODE_VERSION="6"
install:
  - brew update
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
  - npm run install_hugo
script:
  - npm run lint
  - cd exampleSite
  - hugo
notifications:
  slack:
    rooms:
      - devcows:Qs59B9IYFi3IfrejVqNlN5G7#general
